/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkoutSchedule {
    workoutDetails: string;
    setRows: Array<SetRow>;
    owner: Principal;
    dayOfWeek: DayOfWeek;
    completed: boolean;
    timeReminder?: string;
    workoutName: string;
}
export interface TierProgressionResult {
    direction: Variant_up_down_same;
    previousTier: Tier;
    newTier: Tier;
}
export interface SetRow {
    id: bigint;
    completed: boolean;
    description: string;
}
export interface MotivationalMessage {
    id: bigint;
    message: string;
}
export interface Tier {
    name: string;
    index: bigint;
}
export interface UserProfile {
    lastEvaluatedWeek: bigint;
    notificationsEnabled: boolean;
    displayName: string;
    currentTier: bigint;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_up_down_same {
    up = "up",
    down = "down",
    same = "same"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Assign a role to a user. Admin only.
     */
    assignRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create or update a workout schedule entry. Only authenticated users may call this.
     */
    createOrUpdateWorkoutSchedule(id: string, schedule: WorkoutSchedule): Promise<void>;
    /**
     * / Delete a workout schedule entry. Only the owner may delete their own entry.
     */
    deleteWorkoutSchedule(id: string): Promise<void>;
    /**
     * / Evaluate and advance the caller's tier progression for a specific week.
     * / Requires authenticated user.
     */
    evaluateAndAdvanceTier(weekNumber: bigint): Promise<TierProgressionResult>;
    /**
     * / Evaluate a specific user's tier progression for a specific week (admin-only).
     */
    evaluateUserTierProgression(user: Principal, weekNumber: bigint, completedDays: bigint): Promise<TierProgressionResult>;
    /**
     * / Fetch all motivational messages. Available to all callers including guests.
     */
    getAllMotivationalMessages(): Promise<Array<MotivationalMessage>>;
    /**
     * / Get the caller's own profile. Requires authenticated user.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a motivational message by id. Available to all callers including guests.
     */
    getMotivationalMessage(id: bigint): Promise<MotivationalMessage>;
    /**
     * / Fetch a random motivational message by cycling through available ids.
     */
    getRandomMotivationalMessage(): Promise<MotivationalMessage>;
    /**
     * / Get a specific user's profile. Callers may only view their own profile unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Get the caller's current tier without modifying it. Requires authenticated user.
     */
    getUserTier(): Promise<Tier>;
    /**
     * / Returns all workout schedule entries owned by the caller.
     */
    getWorkoutSchedules(): Promise<Array<WorkoutSchedule>>;
    /**
     * / Check whether the caller is an admin.
     */
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Only for backwards compatibility with the original model (Motoko allows
     * / for null queries). This method should be preferred over getting the
     * / profile directly.
     */
    isNotificationsEnabled(): Promise<boolean>;
    /**
     * / Update a specific set row as complete or incomplete. Only the owner may do this.
     */
    markSetRowComplete(workoutId: string, rowId: bigint, completed: boolean): Promise<void>;
    /**
     * / Mark a specific workout as complete or incomplete. Only the owner may do this.
     */
    markWorkoutComplete(id: string, completed: boolean): Promise<void>;
    /**
     * / Save (upsert) the caller's own profile. Requires authenticated user.
     * / Preserves existing tier and lastEvaluatedWeek data to prevent users from resetting their tier.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DayOfWeek as _DayOfWeek, SetRow as _SetRow, Tier as _Tier, TierProgressionResult as _TierProgressionResult, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutSchedule as _WorkoutSchedule } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateWorkoutSchedule(arg0: string, arg1: WorkoutSchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateWorkoutSchedule(arg0, to_candid_WorkoutSchedule_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateWorkoutSchedule(arg0, to_candid_WorkoutSchedule_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteWorkoutSchedule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutSchedule(arg0);
            return result;
        }
    }
    async evaluateAndAdvanceTier(arg0: bigint): Promise<TierProgressionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.evaluateAndAdvanceTier(arg0);
                return from_candid_TierProgressionResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.evaluateAndAdvanceTier(arg0);
            return from_candid_TierProgressionResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async evaluateUserTierProgression(arg0: Principal, arg1: bigint, arg2: bigint): Promise<TierProgressionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.evaluateUserTierProgression(arg0, arg1, arg2);
                return from_candid_TierProgressionResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.evaluateUserTierProgression(arg0, arg1, arg2);
            return from_candid_TierProgressionResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMotivationalMessages(): Promise<Array<MotivationalMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMotivationalMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMotivationalMessages();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMotivationalMessage(arg0: bigint): Promise<MotivationalMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationalMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationalMessage(arg0);
            return result;
        }
    }
    async getRandomMotivationalMessage(): Promise<MotivationalMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomMotivationalMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomMotivationalMessage();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTier(): Promise<Tier> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTier();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTier();
            return result;
        }
    }
    async getWorkoutSchedules(): Promise<Array<WorkoutSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSchedules();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSchedules();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isNotificationsEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isNotificationsEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isNotificationsEnabled();
            return result;
        }
    }
    async markSetRowComplete(arg0: string, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSetRowComplete(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSetRowComplete(arg0, arg1, arg2);
            return result;
        }
    }
    async markWorkoutComplete(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWorkoutComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWorkoutComplete(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_DayOfWeek_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TierProgressionResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierProgressionResult): TierProgressionResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSchedule_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSchedule): WorkoutSchedule {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workoutDetails: string;
    setRows: Array<_SetRow>;
    owner: Principal;
    dayOfWeek: _DayOfWeek;
    completed: boolean;
    timeReminder: [] | [string];
    workoutName: string;
}): {
    workoutDetails: string;
    setRows: Array<SetRow>;
    owner: Principal;
    dayOfWeek: DayOfWeek;
    completed: boolean;
    timeReminder?: string;
    workoutName: string;
} {
    return {
        workoutDetails: value.workoutDetails,
        setRows: value.setRows,
        owner: value.owner,
        dayOfWeek: from_candid_DayOfWeek_n16(_uploadFile, _downloadFile, value.dayOfWeek),
        completed: value.completed,
        timeReminder: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.timeReminder)),
        workoutName: value.workoutName
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: {
        up: null;
    } | {
        down: null;
    } | {
        same: null;
    };
    previousTier: _Tier;
    newTier: _Tier;
}): {
    direction: Variant_up_down_same;
    previousTier: Tier;
    newTier: Tier;
} {
    return {
        direction: from_candid_variant_n9(_uploadFile, _downloadFile, value.direction),
        previousTier: value.previousTier,
        newTier: value.newTier
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    down: null;
} | {
    same: null;
}): Variant_up_down_same {
    return "up" in value ? Variant_up_down_same.up : "down" in value ? Variant_up_down_same.down : "same" in value ? Variant_up_down_same.same : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSchedule>): Array<WorkoutSchedule> {
    return value.map((x)=>from_candid_WorkoutSchedule_n14(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSchedule_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSchedule): _WorkoutSchedule {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workoutDetails: string;
    setRows: Array<SetRow>;
    owner: Principal;
    dayOfWeek: DayOfWeek;
    completed: boolean;
    timeReminder?: string;
    workoutName: string;
}): {
    workoutDetails: string;
    setRows: Array<_SetRow>;
    owner: Principal;
    dayOfWeek: _DayOfWeek;
    completed: boolean;
    timeReminder: [] | [string];
    workoutName: string;
} {
    return {
        workoutDetails: value.workoutDetails,
        setRows: value.setRows,
        owner: value.owner,
        dayOfWeek: to_candid_DayOfWeek_n5(_uploadFile, _downloadFile, value.dayOfWeek),
        completed: value.completed,
        timeReminder: value.timeReminder ? candid_some(value.timeReminder) : candid_none(),
        workoutName: value.workoutName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
