/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const WorkoutScheduleEntry = IDL.Record({
  'workoutDetails' : IDL.Text,
  'owner' : IDL.Principal,
  'dayOfWeek' : DayOfWeek,
  'completed' : IDL.Bool,
  'timeReminder' : IDL.Opt(IDL.Text),
  'workoutName' : IDL.Text,
});
export const MotivationalMessage = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateWorkoutSchedule' : IDL.Func(
      [IDL.Text, WorkoutScheduleEntry],
      [],
      [],
    ),
  'deleteWorkoutSchedule' : IDL.Func([IDL.Text], [], []),
  'getAllMotivationalMessages' : IDL.Func(
      [],
      [IDL.Vec(MotivationalMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMotivationalMessage' : IDL.Func(
      [IDL.Nat],
      [MotivationalMessage],
      ['query'],
    ),
  'getRandomMotivationalMessage' : IDL.Func(
      [],
      [MotivationalMessage],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutSchedules' : IDL.Func(
      [],
      [IDL.Vec(WorkoutScheduleEntry)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWorkoutComplete' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const WorkoutScheduleEntry = IDL.Record({
    'workoutDetails' : IDL.Text,
    'owner' : IDL.Principal,
    'dayOfWeek' : DayOfWeek,
    'completed' : IDL.Bool,
    'timeReminder' : IDL.Opt(IDL.Text),
    'workoutName' : IDL.Text,
  });
  const MotivationalMessage = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateWorkoutSchedule' : IDL.Func(
        [IDL.Text, WorkoutScheduleEntry],
        [],
        [],
      ),
    'deleteWorkoutSchedule' : IDL.Func([IDL.Text], [], []),
    'getAllMotivationalMessages' : IDL.Func(
        [],
        [IDL.Vec(MotivationalMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMotivationalMessage' : IDL.Func(
        [IDL.Nat],
        [MotivationalMessage],
        ['query'],
      ),
    'getRandomMotivationalMessage' : IDL.Func(
        [],
        [MotivationalMessage],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutSchedules' : IDL.Func(
        [],
        [IDL.Vec(WorkoutScheduleEntry)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWorkoutComplete' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };