/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface MotivationalMessage { 'id' : bigint, 'message' : string }
export interface Tier { 'name' : string, 'index' : bigint }
export interface TierProgressionResult {
  'direction' : { 'up' : null } |
    { 'down' : null } |
    { 'same' : null },
  'previousTier' : Tier,
  'newTier' : Tier,
}
export interface UserProfile {
  'lastEvaluatedWeek' : bigint,
  'notificationsEnabled' : boolean,
  'displayName' : string,
  'currentTier' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutScheduleEntry {
  'workoutDetails' : string,
  'owner' : Principal,
  'dayOfWeek' : DayOfWeek,
  'completed' : boolean,
  'timeReminder' : [] | [string],
  'workoutName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a user. Admin only.
   */
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create or update a workout schedule entry. Only authenticated users may call this.
   */
  'createOrUpdateWorkoutSchedule' : ActorMethod<
    [string, WorkoutScheduleEntry],
    undefined
  >,
  /**
   * / Delete a workout schedule entry. Only the owner may delete their own entry.
   */
  'deleteWorkoutSchedule' : ActorMethod<[string], undefined>,
  /**
   * / Evaluate and advance the caller's tier progression for a specific week.
   * / Requires authenticated user.
   */
  'evaluateAndAdvanceTier' : ActorMethod<[bigint], TierProgressionResult>,
  /**
   * / Evaluate a specific user's tier progression for a specific week (admin-only).
   */
  'evaluateUserTierProgression' : ActorMethod<
    [Principal, bigint, bigint],
    TierProgressionResult
  >,
  /**
   * / Fetch all motivational messages. Available to all callers including guests.
   */
  'getAllMotivationalMessages' : ActorMethod<[], Array<MotivationalMessage>>,
  /**
   * / Get the caller's own profile. Requires authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a motivational message by id. Available to all callers including guests.
   */
  'getMotivationalMessage' : ActorMethod<[bigint], MotivationalMessage>,
  /**
   * / Fetch a random motivational message by cycling through available ids.
   */
  'getRandomMotivationalMessage' : ActorMethod<[], MotivationalMessage>,
  /**
   * / Get a specific user's profile. Callers may only view their own profile unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get the caller's current tier without modifying it. Requires authenticated user.
   */
  'getUserTier' : ActorMethod<[], Tier>,
  /**
   * / Returns all workout schedule entries owned by the caller.
   */
  'getWorkoutSchedules' : ActorMethod<[], Array<WorkoutScheduleEntry>>,
  /**
   * / Check whether the caller is an admin.
   */
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Only for backwards compatibility with the original model (Motoko allows
   * / for null queries). This method should be preferred over getting the
   * / profile directly.
   */
  'isNotificationsEnabled' : ActorMethod<[], boolean>,
  /**
   * / Mark a specific workout as complete or incomplete. Only the owner may do this.
   */
  'markWorkoutComplete' : ActorMethod<[string, boolean], undefined>,
  /**
   * / Save (upsert) the caller's own profile. Requires authenticated user.
   * / Preserves existing tier and lastEvaluatedWeek data to prevent users from resetting their tier.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];